- .changeset/famous-chefs-wonder.md
- package.json
- packages/cli/package.json
- packages/core/package.json
- packages/create-webstone-app/src/index.js
- packages/create-webstone-app/template/package.json
- pnpm-lock.yaml
> Add the Webstone CLI to the app template

- README.md
> docs: Document Webstone development.

- README.md
> docs: document the backstory of Webstone

- packages/create-webstone-app/src/index.js
- packages/create-webstone-app/template/CHANGELOG.md
- packages/create-webstone-app/template/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
This wraps up the first step of the `npm init webstone-app` script which installs the template and initializes the web part of the Webstone project.
> A few final touches to the create-webstone-app script.

- README.md
> docs: document how packages are released

- README.md
> docs: use a never-expiring Discord invitation link

- .changeset/cuddly-ravens-hope.md
- packages/core/package.json
> chore(core): use workspace:* rather than workspace:^

- pnpm-lock.yaml
> chore: update the pnpm-lockfile

- .husky/prepare-commit-msg
> chore: skip commitizen in CI environments

- .changeset/plenty-fireants-lick.md
- packages/create-webstone-app/template/package.json
- pnpm-lock.yaml
> chore(create-webstone-app): always use the latest version of the CLI in the template

- README.md
- package.json
> chore: combine changeset and pnpm install

- .changeset/plenty-bees-deliver.md
- .changeset/slow-ladybugs-shop.md
- packages/create-webstone-app/src/index.js
- packages/create-webstone-app/template/package.json
- packages/create-webstone-app/template/pnpm-workspace.yaml
- pnpm-lock.yaml
- pnpm-workspace.yaml
> chore(create-webstone-app): use pnpm in the template to simplify commands

- .changeset/light-mangos-jam.md
- packages/create-webstone-app/src/index.js
> chore(create-webstone-app): remove the node_modules filter when copying the template

- .changeset/olive-starfishes-do.md
- .gitpod.yml
- packages/cli/README.md
- packages/create-webstone-app/src/index.js
- packages/create-webstone-app/template/package.json
> Develop the `@webstone/cli`

- .gitpod.yml
> chore(gitpod): install the Svelte extension

- .changeset/hip-comics-lick.md
- .gitpod.yml
- packages/cli/src/bin.ts
- packages/cli/src/commands/dev/dev.ts
- packages/cli/src/commands/dev/gitpod/web-patch-svelte-config-js.ts
> docs(cli): provide a changelog entry for the new CLI command

- README.md
- package.json
- packages/create-webstone-app/template/package.json
> chore: enforce pnpm only

- CONTRIBUTING.md
- README.md
- packages/cli/README.md
- packages/core/README.md
- packages/create-webstone-app/README.md
> docs: update README.md files & create a CONTRIBUTING.md

- .changeset/green-dingos-nail.md
- .gitpod.yml
- packages/cli/src/bin.ts
- packages/cli/src/commands/web/svelte-add.ts
> chore(gitpod): wait for the CLI package to be ready in dev mode before using the CLI

- .changeset/quick-mirrors-smoke.md
- packages/cli/src/commands/dev/dev.ts
- packages/create-webstone-app/README.md
> Add a `webstone dev` command

- .changeset/light-toys-tie.md
- packages/cli/package.json
- packages/cli/src/commands/web/delete/page.ts
- packages/create-webstone-app/src/index.js
> Add a `webstone web delete page` CLI command

- packages/cli/package.json
- pnpm-lock.yaml
> Remove Prettier from the cli package.

- .eslintrc.js
- .gitpod.yml
- package.json
- packages/cli/package.json
- packages/cli/src/commands/deploy/web.ts
- packages/cli/src/extensions/web/types.d.ts
- packages/cli/src/toolbox/web/configure/deployment/get-installed-adapter.ts
- packages/create-webstone-app/scripts/esbuild.js
- packages/create-webstone-app/src/index.ts
- packages/create-webstone-app/tests/helpers/create-app-dir.ts
- pnpm-lock.yaml
- tests/e2e/cypress/plugins/index.ts
> Configure ESLint

- package.json
- packages/cli/package.json
- packages/cli/tsconfig.json
- packages/cli/tslint.json
- packages/core/package.json
- packages/core/src/index.ts
- packages/core/tsconfig.json
- packages/create-webstone-app/package.json
- packages/create-webstone-app/template/package.json
- pnpm-lock.yaml
- tsconfig.json
An ad-hoc PR to clean up a few Typescript configuration files.
> Streamline Typescript config

- .github/workflows/release.yml
> Use the `changesets/action@v1` version

- package.json
- pnpm-lock.yaml
> Temporarily downgrade `@types/node`

- .gitpod.yml
- .gitpod/tasks/1-webstone-dev/before.sh
- .gitpod/tasks/1-webstone-dev/command.sh
- .gitpod/tasks/2-app-dev/before.sh
- .gitpod/tasks/2-app-dev/command.sh
- .gitpod/tasks/2-app-dev/init.sh
- .gitpod/tasks/3-app-tests/before.sh
- .gitpod/tasks/3-app-tests/command.sh
> Clean up `.gitpod.yml`

- .gitpod.yml
> Open an additional terminal in `webstone-dev-app`

- .changeset/nasty-adults-train.md
- packages/cli/src/commands/web/api/create.ts
> Hotfix for the `webstone web api create` CLI command

- packages/cli/docs/README.md
> Improve the syntax for optional & mandatory arguments

- .changeset/brave-gifts-think.md
- packages/cli/src/templates/web/api/create/[uid].ejs
- packages/cli/src/templates/web/api/create/index.ejs
- packages/cli/src/templates/web/api/create/lib-types.d.ejs
- packages/create-webstone-app/src/helpers.ts
- pnpm-lock.yaml
> fix: make framework work with newest Sveltekit Version

- .github/workflows/release.yml
- .github/workflows/tests.yml
> ci(github-workflow): upgrade GitHub workflow Node.js version to 16

- .changeset/five-dryers-prove.md
- packages/create-webstone-app/package.json
- pnpm-lock.yaml
> Move prod dependencies out of devDependencies

- .changeset/eleven-terms-double.md
- packages/create-webstone-app/src/helpers.ts
- packages/create-webstone-app/src/index.ts
- packages/create-webstone-app/src/tasks/0-check-system-requirements/index.ts
- packages/create-webstone-app/src/tasks/1-create-app-directory/index.ts
- packages/create-webstone-app/src/tasks/2-prepare-project-structure/index.ts
- packages/create-webstone-app/src/tasks/3-install-app-dependencies/index.ts
- packages/create-webstone-app/src/tasks/index.ts
- packages/create-webstone-app/tests/helpers/copy-template.ts
- packages/create-webstone-app/tests/helpers/create-app-dir.ts
> Gracefully handle missing system requirements

- .changeset/angry-pandas-beam.md
- packages/create-webstone-app/src/tasks/1-create-app-directory/index.ts
- packages/create-webstone-app/src/tasks/index.ts
- packages/create-webstone-app/tests/helpers/create-app-dir.ts
> Resolve Enquirer peer dep

- .changeset/brown-mails-wink.md
- .changeset/two-seas-fetch.md
- .gitpod.yml
- package.json
- packages/cli/src/commands/dev/gitpod/web-patch-svelte-config-js.ts
- packages/cli/src/commands/web/api/create.ts
- packages/cli/src/commands/web/page/create.ts
- packages/cli/src/templates/web/api/create/[uid].ejs
- packages/cli/src/templates/web/api/create/index.ejs
- packages/create-webstone-app/package.json
- pnpm-lock.yaml
- tests/e2e/1-web-pages/create-and-delete.spec.ts
> Fix: newest version of Sveltekit

- .gitpod/tasks/1-webstone-dev/before.sh
- package.json
> Pin Playwright Version

- .changeset/modern-grapes-hear.md
- packages/create-webstone-app/src/tasks/1-create-app-directory/index.ts
- packages/create-webstone-app/tests/helpers/create-app-dir.ts
> Warn, instead of force-empty, the app directory if it's not empty

- packages/create-webstone-app/src/helpers.ts
- packages/create-webstone-app/src/tasks/3-configure-app/plugin.ts
- packages/create-webstone-app/template/plugin/command.ts
- packages/create-webstone-app/template/plugin/extension.ts
- packages/create-webstone-app/template/plugin/tsconfig.json
- packages/create-webstone-app/tests/helpers/configure-plugin.ts
Fixes a couple of small hiccups occurring while creating a plugin
> Minor fixes

- .changeset/rare-flowers-fix.md
- packages/core/package.json
- pnpm-lock.yaml
> Bundle Core package for ESM and CJS

- .changeset/cool-dryers-reflect.md
- packages/create-webstone-app/src/tasks/2-setup-project/plugin.ts
- packages/create-webstone-app/templates/plugin/structure/packages/cli/package.json
> Apply missed code from the new plugin structure PR

- SECURITY.md
> Add security documentation

- README.md
> Add a pre-beta warning

- .github/FUNDING.yml
> Change the GitHub Sponsor to the org

- .changeset/mighty-otters-cheer.md
- packages/cli/src/bin.ts
- packages/create-webstone-app/src/tasks/2-setup-project/plugin.ts
- packages/create-webstone-app/templates/plugin/structure/packages/cli/package.json
- packages/create-webstone-app/tests/helpers/setup-plugin.ts
> Naming Scheme for plugins

- .changeset/six-avocados-develop.md
- packages/create-webstone-app/src/tasks/2-setup-project/plugin.ts
- packages/create-webstone-app/templates/plugin/structure/packages/cli/README.md
- packages/create-webstone-app/templates/plugin/structure/packages/web/README.md
> Add README.md templates for plugin cli and web directories

- .github/workflows/release.yml
- package.json
- packages/cli/package.json
- packages/create-webstone-app/templates/plugin/structure/package.json
- packages/create-webstone-app/templates/plugin/structure/packages/cli/package.json
- packages/plugin-request-logger/package.json
- packages/plugin-request-logger/packages/cli/package.json
> Upgrade to node 20

- .changeset/config.json
- package.json
- pnpm-lock.yaml
> chore: Change the changeset format
